### ISSUE TITLE
KeepNote crashes when going back in note view history

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fracte/keepnote#344]
```
What steps will reproduce the problem?
1.Select a note
2.Go to another note
3.Press the back button to go back to the previous note
4.Crashes

What is the expected output? What do you see instead?
I expect to go back to the other note I was viewing but it crashes instead.

What version of the product are you using? On what operating system?
Latest:0.6.5; Windows 7 x64

Please provide any additional information below.
It does it sometimes, I'm not sure what the specific thing is since I tried to 
duplicate the problem with the same notes but it doesn't seem to be that. There 
must be some issue with handling the history after longer use? Because I reopen 
KeepNote and the feature works fine but it's happened before already.
```

Original issue reported on code.google.com by `theswimm...@gmail.com` on 15 Oct 2010 at 10:39
- Merged into: #394

**Comment by GoogleCodeExporter** [comment]
```
Issue 384 has been merged into this issue.
```

Original comment by `matt.rasmus@gmail.com` on 12 May 2011 at 1:54

**Comment by GoogleCodeExporter** [comment]
```
This is a really strange issue.  I have not encountered crashing on windows due 
to using the forward and backward buttons.  Also people seem to be seeing 
crashing when using links.  A full program crash occurs usually when there is a 
bug in one of the libraries.  A bug in my python code should only produce 
raised exceptions (no hard crashes).  My guess is that gtk is getting upset by 
the quick change in pages.

Perhaps this index is corrupt some how.  Try running "Tools > Update Notebook 
Index" to repair your notebook index, and see if the issue goes away.  Also, 
does this issue happen in every notebook that you use.

If the above fix doesn't work, we can try debug it with a script.  Can someone 
with this issue run the following script.  Open "Tools > Python Prompt" and 
paste the following code in the top part of the window.

for note in window.get_notebook().get_children():
  app.goto_nodeid(note.get_attr("nodeid"))

After pasting the code press ctrl+enter to run it.  Does this script crash 
keepnote?  The expect result is that keepnote will quickly view each note in 
the toplevel of your notebook.

```

Original comment by `matt.rasmus@gmail.com` on 12 May 2011 at 2:04
- Added labels: **ui**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for looking at this - what is gtk? I still get this problem 
intermittently, even though I've now upgraded to KN 0.7.1.

I've tried running the script you gave. KN didn't crash, but nothing happened 
except that I got the following output:
Traceback (most recent call last):
  File "C:\Program Files\KeepNote\extensions\python_prompt\dialog_python.py", line 244, in execute
  File "<string>", line 2, in <module>
AttributeError: 'KeepNote' object has no attribute 'goto_nodeid'

I've now rebuilt the index, as you suggested, but it's too soon to know whether 
that's solved the problem. I'll keep you posted!
```

Original comment by `john_he...@hotmail.com` on 12 May 2011 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
ok thanks for trying it out.  I actually made a mistake with the script.  It 
should only work on for my latest testing version 0.7.2.  version 0.7.1 doesn't 
have that function yet.

http://keepnote.org/keepnote/download-test

But my guess is that the index needed to be rebuilt.  Let me know what you find 
out.

p.s. gtk is the library I use for the widgets.
```

Original comment by `matt.rasmus@gmail.com` on 12 May 2011 at 4:03

**Comment by GoogleCodeExporter** [comment]
```
I've tried the script and it works fine for 0.7.2.

Rebuilding my index hasn't helped.

The specific problem seems to have some corollaries:

If I link from a note to another note with the same parent, then click back, 
the back button first just returns the current note to the top of the file and 
enables the forward button. Then the second click of the back button causes a 
crash.

In my test notebook, if I link to a note with a *different* parent, then the 
crash is immediate.

In my lab notebook (the one I use), some links don't seem to cause any problems 
at all - provided they are not to notes which have the same parent.
```

Original comment by `W.Roues...@gmail.com` on 12 May 2011 at 4:13

**Comment by GoogleCodeExporter** [comment]
```
Please try the latest testing version 0.7.6 to see if this is now fixed:
http://keepnote.org/#download-test

```

Original comment by `matt.rasmus@gmail.com` on 19 Sep 2011 at 2:48
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
I'm not sure what to test matt. The other bug reports appear to not have issues 
anymore. I will try testing what they have but I haven't had issues with KN for 
a while in regards to these types of crashes.
```

Original comment by `theswimm...@gmail.com` on 20 Sep 2011 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
Ok. that sounds great.  If you get this bug again, just reopen the issue.  
Thanks!  Matt
```

Original comment by `matt.rasmus@gmail.com` on 20 Sep 2011 at 1:32
- Added labels: **win**
